#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -l nodes=1:ppn=1
#PBS -o logs/log_frames.txt
#PBS -q batch


# --mca btl_tcp_if_include p3p2 tells batchnew nodes which network interface to use
#   batch is infiniband (ib0?), batchnew is just a private ethernet network
mpi=/usr/local/bin/mpirun # Which MPI to run
pyt=/shared/users/asousa/software/python2/bin/python
cmd=/shared/users/asousa/WIPP/lightning_power_study/python/gen_movie_frames_v2.py  # Which file to run


# $mpi $pyt $cmd >> /shared/users/asousa/WIPP/WIPP_stencils/python/logs/stencils_live_array_${PBS_ARRAYID}.txt
lf=/shared/users/asousa/WIPP/lightning_power_study/python/logs/movie_frames_${inlat}_kp${kp}.txt

# $mpi --mca btl_tcp_if_include p3p2 $pyt $cmd ${inlat} >> $lf
$mpi $pyt $cmd ${inlat} >> $lf
